// clkctr_s.v

// Generated using ACDS version 14.1 186 at 2020.08.11.19:31:22

`timescale 1 ps / 1 ps
module clkctr_s (
		input  wire  inclk,  //  altclkctrl_input.inclk
		output wire  outclk  // altclkctrl_output.outclk
	);

	clkctr_s_altclkctrl_0 altclkctrl_0 (
		.inclk  (inclk),  //  altclkctrl_input.inclk
		.outclk (outclk)  // altclkctrl_output.outclk
	);

endmodule
